name: Typography Persistence Tests

on:
  push:
    branches: [main, master]
    paths:
      - 'app/master-controller/**'
      - 'app/api/master-controller/typography/**'
      - 'tests/e2e/master-controller-typography-persistence.spec.ts'
  pull_request:
    branches: [main, master]
    paths:
      - 'app/master-controller/**'
      - 'app/api/master-controller/typography/**'
      - 'tests/e2e/master-controller-typography-persistence.spec.ts'
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    name: E2E Typography Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Typography Persistence Tests
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          npx playwright test master-controller-typography-persistence \
            --project=${{ matrix.browser }} \
            --reporter=html,json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 30

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots-${{ matrix.browser }}
          path: test-results/
          retention-days: 30

      - name: Comment PR with test results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('test-results.json', 'utf8'));

            const body = `
            ## 🧪 Typography Persistence Tests - ${{ matrix.browser }}

            **Status:** ${results.passed ? '✅ PASSED' : '❌ FAILED'}
            **Tests Passed:** ${results.stats.passed}/${results.stats.expected}
            **Duration:** ${results.stats.duration}ms

            ${results.passed ? '' : `
            ### ⚠️ Failed Tests
            ${results.failures.map(f => `- ${f.title}`).join('\n')}

            **Critical:** Typography settings are NOT persisting correctly!
            This PR should NOT be merged until tests pass.
            `}

            [View full report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Fail workflow if tests failed
        if: failure()
        run: |
          echo "❌ Typography persistence tests FAILED"
          echo "🚨 CRITICAL: Typography settings will NOT persist for users"
          echo "🛑 DO NOT DEPLOY until tests pass"
          exit 1

  notify:
    name: Notify on Failure
    needs: test
    if: failure()
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            🚨 CRITICAL TEST FAILURE

            Test: Typography Settings Persistence
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            Typography settings are NOT persisting correctly!
            DO NOT DEPLOY until this is fixed.

            View: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

      - name: Send email notification
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 🚨 CRITICAL - Typography Tests Failed on ${{ github.ref_name }}
          to: ${{ secrets.ALERT_EMAIL }}
          from: GitHub Actions
          body: |
            CRITICAL TEST FAILURE

            The typography settings persistence tests have FAILED.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}

            This means typography settings are NOT saving correctly,
            and users will lose their customizations on page refresh.

            Action Required:
            1. Review failed test output
            2. Check /api/master-controller/typography route
            3. Verify database writes
            4. Fix and re-run tests before deployment

            View full report:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
