'use client';

import React, { useState, useEffect } from 'react';
// TODO: Store imports removed for monorepo - needs Context provider pattern
// import { useTypographyStore } from '@/app/master-controller/stores/typographyStore';
// import { useBrandColorsStore } from '@/app/master-controller/stores/brandColorsStore';

export interface SecondaryButtonProps {
  href?: string;
  children: React.ReactNode;
  className?: string;
  onClick?: (e: React.MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => void;
  as?: 'a' | 'button';
}

/**
 * Secondary Button Component (Converted from WordPress origin)
 *
 * Secondary action button with side glow animations.
 * Preserves exact WordPress styling and animations.
 *
 * @example
 * <SecondaryButton href="/learn-more">Learn More</SecondaryButton>
 * <SecondaryButton as="button" onClick={handler}>Click Me</SecondaryButton>
 */
export function SecondaryButton({ href = '#', children, className = '', onClick, as = 'a' }: SecondaryButtonProps) {
  const [isClicked, setIsClicked] = useState(false);
  const [isHovered, setIsHovered] = useState(false);
  const [leftGlowDelay, setLeftGlowDelay] = useState('0s');
  const [rightGlowDelay, setRightGlowDelay] = useState('0s');

  useEffect(() => {
    const leftDelay = Math.random() * 3; // 0 to 3 seconds for left glow
    const rightDelay = Math.random() * 3; // 0 to 3 seconds for right glow (independent)
    setLeftGlowDelay(`${leftDelay.toFixed(2)}s`);
    setRightGlowDelay(`${rightDelay.toFixed(2)}s`);
  }, []);

  // Brand colors for glow effects (keep hardcoded for animation compatibility)
  const brandGold = '#ffd700';
  const brandGreen = '#00ff88';

  const handleClick = (e: React.MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => {
    setIsClicked(true);
    setTimeout(() => setIsClicked(false), 3000);
    onClick?.(e);
  };

  // Extract width classes from className to apply to button element
  const widthMatch = className?.match(/(min-w-\[[\d]+px\]|w-full|w-\[[\d]+px\])/);
  const widthClass = widthMatch ? widthMatch[0] : '';

  const buttonClasses = `
    relative flex justify-center items-center
    ${widthClass}
    h-[56px] px-5 py-2
    bg-[rgb(45,45,45)] backdrop-blur-[15px]
    rounded-xl border-t border-b border-white/10
    text-button uppercase tracking-wide
    z-10
    shadow-[0_15px_15px_rgba(0,0,0,0.3),inset_0_1px_0_rgba(255,255,255,0.1),inset_0_-1px_0_rgba(0,0,0,0.5)]
    transition-all duration-500
    overflow-hidden

    before:content-[''] before:absolute before:inset-0
    before:bg-gradient-to-l before:from-white/15 before:to-transparent
    before:w-1/2 before:skew-x-[45deg]

    ${isClicked ? 'clicked' : ''}
  `;

  // Button styles - using CSS variables from Master Controller
  // CRITICAL: Use inline styles for properties that Tailwind v4 isn't generating
  const buttonStyles = {
    color: 'var(--text-color-button, var(--color-headingText))',
    fontSize: 'var(--font-size-button, 20px)',
    fontFamily: 'var(--font-family-button, var(--font-taskor), Taskor, system-ui, sans-serif)',
    fontWeight: 'var(--font-weight-button, 600)' as any,
    textTransform: 'var(--text-transform-button, uppercase)' as any,
    letterSpacing: 'var(--letter-spacing-button, 0.05em)',
    lineHeight: 'var(--line-height-button, 1.4)',
    // Inline styles for properties not generated by Tailwind v4
    height: '56px',
    backgroundColor: 'rgb(45,45,45)',
    backdropFilter: 'blur(15px)',
    boxShadow: '0 15px 15px rgba(0,0,0,0.3), inset 0 1px 0 rgba(255,255,255,0.1), inset 0 -1px 0 rgba(0,0,0,0.5)'
  };

  const ButtonElement = as === 'button' ? 'button' : 'a';

  return (
    <div className="py-2">
      <div
        className={`
          ${className}
          group
          relative flex justify-center items-center
          !my-[10px]
        `}
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      >
      <ButtonElement
        {...(as === 'a' ? { href } : { type: 'button' as const })}
        onClick={handleClick}
        className={buttonClasses}
        style={buttonStyles}
      >
        {children}
      </ButtonElement>

      {/* Left side glow bar - GPU COMPOSITED */}
      <div
        className="light-bar"
        style={{
          position: 'absolute',
          top: '50%',
          left: '-5px',
          width: '10px',
          height: '44.8px', // 80% of 56px - base size
          borderRadius: '6px',
          transform: `translateY(-50%) scale(${isHovered ? 1 : 0.4018})`, // Firefox-compatible: removed translateZ(0) and using scale() instead of scaleY()
          background: isClicked ? brandGreen : '#ffd700',
          boxShadow: isClicked
            ? `0 0 5px ${brandGreen}, 0 0 15px ${brandGreen}, 0 0 30px ${brandGreen}, 0 0 60px ${brandGreen}`
            : '0 0 5px #ffd700, 0 0 15px #ffd700, 0 0 30px #ffd700, 0 0 60px #ffd700',
          transition: 'transform 0.3s ease-in-out, background 0.3s ease-in-out, box-shadow 0.3s ease-in-out',
          willChange: 'transform',
          ...(isClicked ? {} : { '--pulse-delay': leftGlowDelay } as any),
        }}
        data-pulse-active={!isClicked}
      />

      {/* Right side glow bar - GPU COMPOSITED */}
      <div
        className="light-bar"
        style={{
          position: 'absolute',
          top: '50%',
          right: '-5px',
          width: '10px',
          height: '44.8px', // 80% of 56px - base size
          borderRadius: '6px',
          transform: `translateY(-50%) scale(${isHovered ? 1 : 0.4018})`, // Firefox-compatible: removed translateZ(0) and using scale() instead of scaleY()
          background: isClicked ? brandGreen : '#ffd700',
          boxShadow: isClicked
            ? `0 0 5px ${brandGreen}, 0 0 15px ${brandGreen}, 0 0 30px ${brandGreen}, 0 0 60px ${brandGreen}`
            : '0 0 5px #ffd700, 0 0 15px #ffd700, 0 0 30px #ffd700, 0 0 60px #ffd700',
          transition: 'transform 0.3s ease-in-out, background 0.3s ease-in-out, box-shadow 0.3s ease-in-out',
          willChange: 'transform',
          ...(isClicked ? {} : { '--pulse-delay': rightGlowDelay } as any),
        }}
        data-pulse-active={!isClicked}
      />

      <style jsx>{`
        /* Light bar positioning */
        .light-bar {
          z-index: 1;
        }

        /* Pseudo-element for glow effect - GPU COMPOSITED - this is what pulses */
        .light-bar::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          background: inherit;
          filter: blur(15px);
          opacity: 0.8;
          z-index: -1;
          /* Removed translateZ(0) - Firefox doesn't like mixing 3D/2D transforms */
          will-change: transform, opacity; /* Hint for compositor */
        }

        /* Pulsing animation for glow only - DRAMATIC - uses compositor-friendly properties */
        /* Firefox-compatible: using scale() only, no translateZ() */
        @keyframes lightPulse {
          0%, 100% {
            opacity: 1;
            transform: scale(1);
          }
          50% {
            opacity: 0.3;
            transform: scale(1.8);
          }
        }

        /* Apply animation ONLY to pseudo-element when pulse is active */
        .light-bar[data-pulse-active="true"]::before {
          animation: lightPulse 1s ease-in-out infinite;
          animation-delay: var(--pulse-delay, 0s);
        }
      `}</style>
      </div>
    </div>
  );
}
