name = "saabuildingblocks"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

# Cloudflare Pages configuration for Next.js deployment
# Uses @cloudflare/next-on-pages adapter to run full Next.js on Workers

[env.production]
name = "saabuildingblocks"
route = "saabuildingblocks.com/*"

# Environment variables are set in Cloudflare dashboard
# Required: WORDPRESS_USER, WORDPRESS_APP_PASSWORD, NEXT_PUBLIC_WORDPRESS_API_URL
