/**
 * Blog data loader for Astro build time.
 * Reads chunked JSON files generated by generate-blog-posts-json.ts
 * from the public-site package.
 */
import type { BlogPost } from './wordpress/types';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

const AUTHOR_NAME_MAP: Record<string, string> = {
  'karriehill': 'Karrie Hill',
  'dougsmart1': 'Doug Smart',
};

function normalizeAuthorName(post: BlogPost): BlogPost {
  const mapped = AUTHOR_NAME_MAP[post.author.name.toLowerCase()];
  if (mapped) {
    return { ...post, author: { ...post.author, name: mapped } };
  }
  return post;
}

/**
 * Load all blog posts from the public-site's chunked JSON files.
 * Falls back to astro-site/public/ if public-site chunks don't exist.
 */
export function getAllBlogPosts(): BlogPost[] {
  const allPosts: BlogPost[] = [];

  // Try public-site first, then astro-site public
  const publicSiteDir = join(process.cwd(), '..', 'public-site', 'public');
  const astroPublicDir = join(process.cwd(), 'public');
  const publicDir = existsSync(join(publicSiteDir, 'blog-posts-index.json'))
    ? publicSiteDir
    : astroPublicDir;

  const indexPath = join(publicDir, 'blog-posts-index.json');
  let totalChunks = 50;
  try {
    if (existsSync(indexPath)) {
      const index = JSON.parse(readFileSync(indexPath, 'utf-8'));
      totalChunks = index.totalChunks || totalChunks;
    }
  } catch {}

  for (let i = 1; i <= totalChunks; i++) {
    const chunkPath = join(publicDir, `blog-posts-chunk-${i}.json`);
    try {
      if (existsSync(chunkPath)) {
        const data: BlogPost[] = JSON.parse(readFileSync(chunkPath, 'utf-8'));
        allPosts.push(...data.map(normalizeAuthorName));
      }
    } catch (error) {
      console.warn(`Failed to load blog-posts-chunk-${i}.json:`, error);
    }
  }

  console.log(`Loaded ${allPosts.length} blog posts from ${totalChunks} chunks`);
  return allPosts;
}

let cachedPosts: BlogPost[] | null = null;
export function getCachedBlogPosts(): BlogPost[] {
  if (!cachedPosts) {
    cachedPosts = getAllBlogPosts();
  }
  return cachedPosts;
}

export function getRelatedPosts(
  posts: BlogPost[],
  currentPost: BlogPost,
  limit = 6
): BlogPost[] {
  const currentCategory = currentPost.categories[0];
  const candidates = posts.filter((p) => p.id !== currentPost.id);
  const sameCategory = candidates.filter((p) =>
    p.categories.includes(currentCategory)
  );
  const other = candidates.filter(
    (p) => !p.categories.includes(currentCategory)
  );
  const sorted = [...sameCategory, ...other].slice(0, limit);

  return sorted.map((p) => ({
    ...p,
    content: '',
  }));
}

export function findPostBySlug(posts: BlogPost[], slug: string): BlogPost | undefined {
  const byUri = posts.find((p) => {
    if (!p.customUri) return false;
    const uriSlug = p.customUri.split('/').pop();
    return uriSlug === slug;
  });
  if (byUri) return byUri;
  return posts.find((p) => p.slug === slug);
}
